name: Generate Windows Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - run: pip install -r dependencies/requirements.txt pyinstaller
      - run: |
          set PYTHONUTF8=1
          chcp 65001
          set PYTHONIOENCODING=utf-8
          pyinstaller main.py --onefile -w --icon assets\icons\icon.ico
          copy dist\main.exe TSH.exe

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add TSH.exe
          git commit -m "Update exe" -a

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
